name: Build and Deploy
run-name: Build and Deploy ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      GO_VERSION: 1.23
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ env.GO_VERSION }}

      - name: Audit repository
        run: make audit

  docker-build-and-push:
    if: startsWith(github.ref, 'refs/tags/')
    env:
      DOCKER_TAG: ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Tag Docker Image ${{ github.ref_name }}
        run: |
          make docker-build

      - name: Test Docker Container
        run: |
          make docker-run

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker Image ${{ github.ref_name }}
        run: |
          make docker-push
